site_name: 'Progressbar'
site_description: 'A terminal progress bar for Java/JVM'
site_author: 'Tongfei Chen'
copyright: 'Copyright &copy; 2015-2022 Tongfei Chen and contributors'

theme:
  name: 'material'
  palette:
    primary: green
    accent: indigo
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'
  icon:
    logo: material/chart-donut
  
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed

repo_name: 'ctongfei/progressbar'
repo_url: 'https://github.com/ctongfei/progressbar'

extra_css: []

nav:
  - 'Introduction': 'index.md'
  - 'Declarative usage': 'declarative-usage.md'
  - 'Imperative usage': 'imperative-usage.md'
  - 'Visual styles': 'styles.md'
  - 'Builder pattern': 'builder.md'
  - 'Kotlin extensions': 'kotlin.md'
  - 'Integrating with loggers': 'loggers.md'
  - 'Changelog': 'changelog.md'
