site_name: 'Progressbar 0.8.0'
site_description: 'A console progress bar for Java/JVM'
site_author: 'Tongfei Chen'
copyright: 'Copyright &copy; 2015-2019 Tongfei Chen'

theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'
  logo:
    icon: data_usage
  
markdown_extensions: 
  - codehilite
  - extra
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'

repo_name: 'ctongfei/progressbar'
repo_url: 'https://github.com/ctongfei/progressbar'

extra_css: ['css/extra.css']

pages:
  - 'Introduction': 'index.md'
  - 'Declarative usage': 'declarative-usage.md'
  - 'Imperative usage': 'imperative-usage.md'
  - 'Visual styles': 'styles.md'
  - 'Builder pattern': 'builder.md'
  - 'Changelog': 'changelog.md'
